# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabCo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('office_cood_x', models.DecimalField(decimal_places=4, max_digits=7)),
                ('office_cood_y', models.DecimalField(decimal_places=4, max_digits=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('reply', models.TextField()),
                ('seq_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuerySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField()),
                ('status', models.BooleanField()),
                ('loc_cood_x', models.DecimalField(decimal_places=4, max_digits=7)),
                ('loc_cood_y', models.DecimalField(decimal_places=4, max_digits=7)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_cood_x', models.DecimalField(decimal_places=4, max_digits=7)),
                ('home_cood_y', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mobile_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('mobile_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SparesDealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TowingCo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('phone_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('phone_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TowingVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_1', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('mobile_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('loc_cood_x', models.DecimalField(decimal_places=4, max_digits=7)),
                ('loc_cood_y', models.DecimalField(decimal_places=4, max_digits=7)),
                ('towco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TowingCo')),
            ],
        ),
        migrations.AddField(
            model_name='query',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Requester'),
        ),
        migrations.AddField(
            model_name='query',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.QuerySession'),
        ),
    ]
