# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysession',
            name='service_code',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='querysession',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
